
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "xullgeycueouyxeirrqs"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns in a single REST request.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by the database to listen for connections.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
enabled = true
# Port to use for the Studio URL.
port = 54323
# External URL of the API server that Studio should use. Defaults to the api.port.
api_url = "http://localhost:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the inbucket API.
port = 54324
# Port to use for the inbucket SMTP server.
smtp_port = 54325
# Port to use for the inbucket POP3 server.
pop3_port = 54326
# Port to use for the inbucket web interface.
web_port = 54327
# Web URL for the inbucket web interface. Studio will use this URL to navigate to the inbucket web
# interface.
web_url = "http://localhost:54327"

[storage]
enabled = true
# The upload limit for storage (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow managing user data from the dashboard.
enable_dashboard_user_management = true

[functions]
enabled = true
port = 54328

# Vector and extensions are not yet generally available on Supabase, keep disabled until they are.
[vector]
enabled = false

[extensions]
enabled = false
