
version: '3.8'

services:
  # Frontend React application with hot reloading
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  # Backend FastAPI service
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ems
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - db
      - mqtt-broker

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ems
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # MQTT broker
  mqtt-broker:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

volumes:
  pgdata:
