name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main  # or the branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Supabase CLI (official method)
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy aggregate-modbus function
        run: supabase functions deploy aggregate-modbus --project-ref xullgeycueouyxeirrqs
