name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main  # Trigger only on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🛠 Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase CLI
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}


      - name: 🚀 Deploy Edge Function (aggregate-modbus)
        run: supabase functions deploy aggregate-modbus --project-ref xullgeycueouyxeirrqs
