name: Run Data Cleaning Function

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  workflow_dispatch:

jobs:
  data-cleaning:
    runs-on: ubuntu-latest
    steps:
      - name: Run Data Cleaning Function
        run: |
          curl -L -X POST 'https://xullgeycueouyxeirrqs.supabase.co/functions/v1/data-cleaning' \
          -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
          -H 'Content-Type: application/json'
