name: Run MQTT Agent

on:
  push:
    paths:
      - 'mqtt-agent/**'
      - '.github/workflows/run-mqtt-agent.yml'

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t mqtt-agent ./mqtt-agent

      - name: Run MQTT Agent
        run: |
          docker run --env-file ./mqtt-agent/.env mqtt-agent
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          MQTT_BROKER_URL: ${{ secrets.MQTT_BROKER_URL }}
