name: Run MQTT Ingestion

on:
  workflow_dispatch:  # Can be triggered manually from GitHub UI

jobs:
  mqtt-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: mqtt-ingestion
        run: npm install

      - name: Run MQTT ingestion service
        working-directory: mqtt-ingestion
        env:
          MQTT_BROKER_URL: ${{ secrets.MQTT_BROKER_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run: node index.js
